import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: process.env.NODE_ENV === 'production' ? '/Portfolio/girl-icon.png' : '/girl-icon.png',
    shortcut: process.env.NODE_ENV === 'production' ? '/Portfolio/girl-icon.png' : '/girl-icon.png',
    apple: process.env.NODE_ENV === 'production' ? '/Portfolio/girl-icon.png' : '/girl-icon.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
